src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private bool $isVerified = false;

    /**
     * @var Collection<int, SmsMessage>
     */
    #[ORM\OneToMany(targetEntity: SmsMessage::class, mappedBy: 'user')]
    private Collection $smsMessages;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $accessToken = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $number = null;

    #[ORM\Column]
    private ?bool $isNumberVerified = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $numberToken = null;

    #[ORM\Column(nullable: true)]
    private ?int $numberTemporalCode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $resetPasswordToken = null;

    public function __construct()
    {
        $this->smsMessages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, SmsMessage>
     */
    public function getSmsMessages(): Collection
    {
        return $this->smsMessages;
    }

    public function addSmsMessage(SmsMessage $smsMessage): static
    {
        if (!$this->smsMessages->contains($smsMessage)) {
            $this->smsMessages->add($smsMessage);
            $smsMessage->setUser($this);
        }

        return $this;
    }

    public function removeSmsMessage(SmsMessage $smsMessage): static
    {
        if ($this->smsMessages->removeElement($smsMessage)) {
            // set the owning side to null (unless already changed)
            if ($smsMessage->getUser() === $this) {
                $smsMessage->setUser(null);
            }
        }

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->accessToken;
    }

    public function setAccessToken(?string $accessToken): static
    {
        $this->accessToken = $accessToken;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function isNumberVerified(): ?bool
    {
        return $this->isNumberVerified;
    }

    public function setNumberVerified(bool $isNumberVerified): static
    {
        $this->isNumberVerified = $isNumberVerified;

        return $this;
    }

    public function getNumberToken(): ?string
    {
        return $this->numberToken;
    }

    public function setNumberToken(?string $numberToken): static
    {
        $this->numberToken = $numberToken;

        return $this;
    }

    public function getNumberTemporalCode(): ?int
    {
        return $this->numberTemporalCode;
    }

    public function setNumberTemporalCode(?int $numberTemporalCode): static
    {
        $this->numberTemporalCode = $numberTemporalCode;

        return $this;
    }

    public function getResetPasswordToken(): ?string
    {
        return $this->resetPasswordToken;
    }

    public function setResetPasswordToken(?string $resetPasswordToken): static
    {
        $this->resetPasswordToken = $resetPasswordToken;

        return $this;
    }
}

src/Controller/SmsController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use App\Repository\SmsMessageRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted("IS_AUTHENTICATED_FULLY")]
#[Route('/sms')]
class SmsController extends AbstractController
{

    public function __construct(
        private readonly SmsMessageRepository $smsMessageRepository,
        private readonly PaginatorInterface $paginator
    )
    {
    }

    #[Route('/', name: 'sms_index')]
    public function index(#[CurrentUser] User $user, Request $request): Response
    {
        $sms = $this->paginator->paginate(
            $this->smsMessageRepository->findByUser($user),
            $request->query->getInt('page', 1),
            10,
        );
        return $this->render('pages/sms/sms-index.html.twig', [
            'sms' => $sms,
        ]);
    }
}

templates/pages/sms/sms-index.html.twig
{% extends "base.html.twig" %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}}
{% endblock %}

{% block title %} Sms {% endblock %}


{% block content_header %}
    <div>
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">SMS</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Accueil</a></li>
                    <li class="breadcrumb-item active">Sms</li>
                </ol>
            </div><!-- /.col -->
        </div>
    </div>
{% endblock %}


{% block content %}
    {% if not app.user.numberVerified %}
        <div class="row">
            <div class="alert alert-warning col-12">
                {{ "token.warning"|trans }}
                <a class="text-primary ml-2" href="{{ path('app_number_register') }}">{{ "btn.number.register"|trans }} ?</a>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12" id="accordion">
            <div class="card card-primary card-outline">
                <a class="d-block w-100">
                    <div class="card-header">
                        <h4 class="card-title w-100">
                           Token
                        </h4>
                    </div>
                </a>
                <div data-parent="#accordion" style="">
                    <div class="card-body">
                        {% include 'includes/_flash_message.html.twig' %}

                        {% set canCreateToken = app.user.numberVerified and app.user.verified %}

                        <div class="my-3">
                            <a  aria-disabled="true" href="{{ canCreateToken ? path('app_user_generate_token') : '#' }}" class="{{  canCreateToken ?: "disabled"}} btn btn-primary">
                                {{ "btn.generate_token"|trans }}
                            </a>
                        </div>

                        {% if app.user.accessToken and  canCreateToken %}
                            <div {{ vue_component('TokenGenerator', {token: app.user.accessToken}) }}></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/sms_message_table.html.twig' %}
{% endblock %}